language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-dev automake libtool autoconf
script: ./travis-build.sh
branches:
  only:
    - master
notifications:
  recipients:
    - herron.philip@googlemail.com
  email:
    on_success: change
    on_failure: always
