/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java7book_chapter7_jni_MessageBox */

#ifndef _Included_com_java7book_chapter7_jni_MessageBox
#define _Included_com_java7book_chapter7_jni_MessageBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java7book_chapter7_jni_MessageBox
 * Method:    show
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_java7book_chapter7_jni_MessageBox_show
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
