/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java7book_chapter7_jni_NativeMath */

#ifndef _Included_com_java7book_chapter7_jni_NativeMath
#define _Included_com_java7book_chapter7_jni_NativeMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java7book_chapter7_jni_NativeMath
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_java7book_chapter7_jni_NativeMath_sqrt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_java7book_chapter7_jni_NativeMath
 * Method:    size
 * Signature: (Lcom/java7book/chapter7/jni/Rectangle;)D
 */
JNIEXPORT jdouble JNICALL Java_com_java7book_chapter7_jni_NativeMath_size
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
